# Generated by Django 4.1.4 on 2023-01-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projects_id_projects_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '项目表', 'verbose_name_plural': '项目表'},
        ),
    ]
